services:
  app:
    image: ${DOCKER_IMAGE:-order-food-web}:${IMAGE_TAG:-latest}
    container_name: order-food-app
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - app

networks:
  app:
    external: true
